Add a --nolock option to raspbmirror.
We need to run raspbmirror on a freebsd box that has the target directory
NFS-mounted, where flock will not work:

Traceback (most recent call last):
  File "/usr/local/bin/raspbmirror.py", line 48, in <module>
    fcntl.flock(lockfd,fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 45] Operation not supported

--nolock lets us move the mutual exclusion outside the script.